export const SPORTS = [
  "Football","Futsal","Basketball","Volleyball","Handball","Tennis","Table Tennis","Padel","Badminton","Swimming","Athletics","Karate","Taekwondo","Judo","Boxing","Wrestling","Gymnastics","Cycling","Running","eSports","Chess","Baseball","Softball","Rugby","Hockey","Cricket","American Football","Other"
] as const;

export const AGE_CATEGORIES = [
  "Under 8","Under 10","Under 12","Under 14","Under 16","Under 18","Under 21","Senior","Veterans"
] as const;

export const COUNTRIES = [
  "Syria", "Lebanon", "Jordan", "Iraq", "Saudi Arabia", "UAE", "Qatar", "Kuwait", "Bahrain", "Oman", "Yemen",
  "Egypt", "Morocco", "Algeria", "Tunisia", "Libya", "Sudan",
  "Turkey", "Iran", "Pakistan", "India", "Bangladesh", "Sri Lanka", "Nepal",
  "China", "Japan", "South Korea", "Indonesia", "Malaysia", "Singapore", "Thailand", "Vietnam", "Philippines",
  "Australia", "New Zealand",
  "United States", "Canada", "Mexico",
  "Brazil", "Argentina", "Chile", "Colombia", "Peru", "Uruguay",
  "United Kingdom", "Ireland", "France", "Germany", "Spain", "Italy", "Portugal", "Netherlands", "Belgium", "Switzerland", "Austria", "Sweden", "Norway", "Denmark", "Finland", "Poland", "Czech Republic", "Romania", "Greece", "Ukraine", "Russia",
  "South Africa", "Nigeria", "Kenya", "Ethiopia", "Ghana"
] as const;

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  Syria: ["Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Tartus", "Daraa", "Deir ez-Zor"],
  Lebanon: ["Beirut", "Tripoli", "Sidon", "Tyre", "Byblos", "Zahle"],
  Jordan: ["Amman", "Zarqa", "Irbid", "Aqaba", "Madaba", "Jerash"],
  Iraq: ["Baghdad", "Basra", "Erbil", "Mosul", "Najaf", "Karbala", "Sulaymaniyah"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Dammam", "Mecca", "Medina", "Khobar", "Abha"],
  UAE: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Al Ain", "Ras Al Khaimah", "Fujairah"],
  Qatar: ["Doha", "Al Rayyan", "Al Wakrah", "Umm Salal"],
  Kuwait: ["Kuwait City", "Hawalli", "Farwaniya", "Jahra"],
  Bahrain: ["Manama", "Muharraq", "Riffa", "Hamad Town"],
  Oman: ["Muscat", "Salalah", "Sohar", "Nizwa"],
  Yemen: ["Sanaa", "Aden", "Taiz", "Hodeidah", "Mukalla"],
  Egypt: ["Cairo", "Alexandria", "Giza", "Mansoura", "Tanta", "Asyut", "Luxor"],
  Morocco: ["Casablanca", "Rabat", "Marrakesh", "Fes", "Tangier", "Agadir"],
  Algeria: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
  Tunisia: ["Tunis", "Sfax", "Sousse", "Bizerte", "Nabeul"],
  Libya: ["Tripoli", "Benghazi", "Misrata", "Sabha"],
  Sudan: ["Khartoum", "Omdurman", "Port Sudan", "Nyala"],
  Turkey: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Gaziantep"],
  Iran: ["Tehran", "Mashhad", "Isfahan", "Tabriz", "Shiraz", "Karaj"],
  Pakistan: ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Faisalabad", "Peshawar"],
  India: ["Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Chennai", "Kolkata", "Pune"],
  Bangladesh: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  "Sri Lanka": ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo"],
  Nepal: ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar"],
  China: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Wuhan", "Hangzhou"],
  Japan: ["Tokyo", "Osaka", "Kyoto", "Yokohama", "Nagoya", "Sapporo"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
  Indonesia: ["Jakarta", "Surabaya", "Bandung", "Medan", "Makassar"],
  Malaysia: ["Kuala Lumpur", "George Town", "Johor Bahru", "Kota Kinabalu"],
  Singapore: ["Singapore"],
  Thailand: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Khon Kaen"],
  Vietnam: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Can Tho", "Hai Phong"],
  Philippines: ["Manila", "Quezon City", "Cebu City", "Davao", "Makati"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton"],
  "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Miami", "Dallas", "San Francisco", "Seattle", "Boston", "Atlanta"],
  Canada: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Edmonton"],
  Mexico: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana"],
  Brazil: ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Belo Horizonte", "Curitiba"],
  Argentina: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza", "La Plata"],
  Chile: ["Santiago", "Valparaiso", "Concepcion", "Antofagasta"],
  Colombia: ["Bogota", "Medellin", "Cali", "Barranquilla", "Cartagena"],
  Peru: ["Lima", "Arequipa", "Cusco", "Trujillo", "Piura"],
  Uruguay: ["Montevideo", "Punta del Este", "Salto", "Paysandu"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Liverpool", "Leeds", "Glasgow"],
  Ireland: ["Dublin", "Cork", "Galway", "Limerick"],
  France: ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Lille"],
  Germany: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Stuttgart"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao", "Malaga"],
  Italy: ["Rome", "Milan", "Naples", "Turin", "Bologna", "Florence"],
  Portugal: ["Lisbon", "Porto", "Braga", "Coimbra"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  Belgium: ["Brussels", "Antwerp", "Ghent", "Liege"],
  Switzerland: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne"],
  Austria: ["Vienna", "Graz", "Salzburg", "Linz"],
  Sweden: ["Stockholm", "Gothenburg", "Malmo", "Uppsala"],
  Norway: ["Oslo", "Bergen", "Trondheim", "Stavanger"],
  Denmark: ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
  Finland: ["Helsinki", "Tampere", "Turku", "Oulu"],
  Poland: ["Warsaw", "Krakow", "Wroclaw", "Gdansk", "Poznan"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzen"],
  Romania: ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi"],
  Greece: ["Athens", "Thessaloniki", "Patras", "Heraklion"],
  Ukraine: ["Kyiv", "Lviv", "Odessa", "Kharkiv", "Dnipro"],
  Russia: ["Moscow", "Saint Petersburg", "Kazan", "Novosibirsk", "Yekaterinburg"],
  "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
  Nigeria: ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt"],
  Kenya: ["Nairobi", "Mombasa", "Kisumu", "Nakuru"],
  Ethiopia: ["Addis Ababa", "Dire Dawa", "Mekelle", "Bahir Dar"],
  Ghana: ["Accra", "Kumasi", "Tamale", "Takoradi"]
};

export const COUNTRY_CODES = [
  "+963", "+961", "+962", "+964", "+966", "+971", "+974", "+965", "+973", "+968", "+967",
  "+20", "+212", "+213", "+216", "+218", "+249",
  "+90", "+98", "+92", "+91", "+880", "+94", "+977",
  "+86", "+81", "+82", "+62", "+60", "+65", "+66", "+84", "+63",
  "+61", "+64",
  "+1", "+52",
  "+55", "+54", "+56", "+57", "+51", "+598",
  "+44", "+353", "+33", "+49", "+34", "+39", "+351", "+31", "+32", "+41", "+43", "+46", "+47", "+45", "+358", "+48", "+420", "+40", "+30", "+380", "+7",
  "+27", "+234", "+254", "+251", "+233"
];

export const COUNTRY_TO_PHONE_CODE: Record<string, string> = {
  Syria: "+963",
  Lebanon: "+961",
  Jordan: "+962",
  Iraq: "+964",
  "Saudi Arabia": "+966",
  UAE: "+971",
  Qatar: "+974",
  Kuwait: "+965",
  Bahrain: "+973",
  Oman: "+968",
  Yemen: "+967",
  Egypt: "+20",
  Morocco: "+212",
  Algeria: "+213",
  Tunisia: "+216",
  Libya: "+218",
  Sudan: "+249",
  Turkey: "+90",
  Iran: "+98",
  Pakistan: "+92",
  India: "+91",
  Bangladesh: "+880",
  "Sri Lanka": "+94",
  Nepal: "+977",
  China: "+86",
  Japan: "+81",
  "South Korea": "+82",
  Indonesia: "+62",
  Malaysia: "+60",
  Singapore: "+65",
  Thailand: "+66",
  Vietnam: "+84",
  Philippines: "+63",
  Australia: "+61",
  "New Zealand": "+64",
  "United States": "+1",
  Canada: "+1",
  Mexico: "+52",
  Brazil: "+55",
  Argentina: "+54",
  Chile: "+56",
  Colombia: "+57",
  Peru: "+51",
  Uruguay: "+598",
  "United Kingdom": "+44",
  Ireland: "+353",
  France: "+33",
  Germany: "+49",
  Spain: "+34",
  Italy: "+39",
  Portugal: "+351",
  Netherlands: "+31",
  Belgium: "+32",
  Switzerland: "+41",
  Austria: "+43",
  Sweden: "+46",
  Norway: "+47",
  Denmark: "+45",
  Finland: "+358",
  Poland: "+48",
  "Czech Republic": "+420",
  Romania: "+40",
  Greece: "+30",
  Ukraine: "+380",
  Russia: "+7",
  "South Africa": "+27",
  Nigeria: "+234",
  Kenya: "+254",
  Ethiopia: "+251",
  Ghana: "+233",
};
